validmind/documentation

.github/workflows/release_notes_check.yml
This PR makes a small tweak to our release notes check so that it runs only if a PR is not in draft mode. This should avoid frequent CI check failures when a PR is in progress. 
Here's how the CI check gets skipped after you change the PR to draft mode and then make a commit: 
And here's what happens when you change the PR back to ready for review:
=> Run release notes check only if not in draft mode

site/guide/faq-documentation.qmd
Updated the FAQ to fix a typo and remove roadmap items.
=> Fixed typo and removed roadmap commitments

site/Makefile
This PR makes it easier for contributors to preview our docs site locally, without having to fetch content from other repos first. 
@robinzimmermann encountered an issue where the Python documentation that gets copied into our docs site in a [post-render step](https://github.com/validmind/documentation/blob/main/site/_quarto.yml#L3) was unavailable locally. This occurred because, as a new contributor, he hadn't run the `make get-source` command to fetch content from the developer-framework repository yet. Consequently, he was unable to preview his changes using `quarto preview`.
Typically, updating the Python documentation is a task for writers preparing to publish the latest version of our docs site, making it unnecessary for contributors like Robin to deal with. To simplify the process …
=> Make it easier for contributors to preview docs site locally

site/guide/swap-documentation-templates.qmd
This PR fixes the issues Robin identified in https://app.shortcut.com/validmind/story/3921/typos-in-swap-documentation-templates-doc. 
No release notes, as these are just some smaller fixes.
=> Fix typos in swap documentation templates doc

site/_site/about/glossary/glossary.html, site/_site/about/style-guide.html, site/_site/guide/developer-getting-started-video.html, site/_site/guide/get-started-developer-framework.html, site/_site/guide/get-started.html, site/_site/guide/guides.html, site/_site/guide/preparing-validation-reports.html, site/_site/guide/quickstart-explore-sample-model-documentation.html, site/_site/guide/quickstart-generate-documentation-for-your-model.html, site/_site/guide/quickstart-register-your-first-model.html, site/_site/guide/quickstart-try-developer-framework-in-your-own-developer-environment.html, site/_site/guide/quickstart-try-developer-framework-with-colab.html, site/_site/guide/quickstart-try-developer-framework-with-jupyterhub.html, site/_site/guide/testing-overview.html, site/_site/guide/working-with-model-documentation.html, site/_site/search.json, site/guide/get-started-developer-framework.qmd, site/guide/quickstart-try-developer-framework-with-jupyterhub.qmd
This PR embeds the new QuickStart video into a couple of places.
Into the QuickStart for JupyterHub:
Into the "Getting started" section for the developer framework:
A new three-minute QuickStart video walks you through documenting a model with ValidMind. We demo how to run our QuickStart notebook on JuypyterHub and show you how to work with model documentation on the ValidMind platform. [Watch it ...](../../guide/quickstart-try-developer-framework-with-jupyterhub.qmd)
=> Add QuickStart video to the docs site

site/_site/guide/guides.html, site/_site/guide/testing-overview.html, site/_site/guide/working-with-model-documentation.html, site/_site/listings.json, site/_site/search.json, site/guide/working-with-model-documentation.qmd
> For sc-4030, added a `Assign documentation section statuses` page.
- Net new page: `documentation-section-statuses.qmd`
- Added page to `_quarto.yml` under "Assign section statuses"
- Updated the contents to include "Assign documentation section statuses" so it shows up in the `What's next` section
- Modified the instructions in the `Get started` section to reflect current UX, including a call-out for documentation summaries at the top of the overview page
| Old | New |
|---|---|
|<img width="795" alt="Screenshot 2024-05-21 at 12 19 44 PM" src="https://github.com/validmind/documentation/assets/164545837/da34141b-939a-4f3c-80b8-ce9618d8e8c0">|<img width="796" alt="Screenshot 2024-05-21 at 12 20 02 PM" src="https://github.com/validmind/documentation/assets/164545837/aa282e74-bdff-4ade-9cdc …
=> New "Assign documentation section statuses" page in Guides

site/Makefile
Was trying to fix the folder name to `nlp_and_llm` and make it still display `NLP and LLM` but that was a sad sad rabbit hole. As per the recent comments on the associated story, I just fixed the file name by editing the Makefile.
The other files changed were just from running `make notebooks` for testing and from running `quarto render` as well.
=> Fixing Makefile to not change nlp_and_llm to NLP_and_LLM

site/_quarto.yml
This PR restores Beck's version of `_quarto.yml` from https://github.com/validmind/documentation/commit/e920cda13d0969f8d3675d1b320b4659283eabb2.
**Context**: while testing @noosheenv's GitHub workflow, I thoroughly børked `_quarto.yml`. Rather than trying to fix it, I simply checked out the file from `main`, thinking I was being very clever. However, that ended up overwriting the site improvement changes from @validbeck when Noosheen's PR got merged. 
I broke it, with an apology. I hope this fix undoes my mistake.
=> Fix issues introduced by checkout of _quarto.yml

README.md, site/styles.css
> sc-5449
| Old | New |
|---|---|
| <img width="934" alt="Screenshot 2024-07-15 at 11 08 50 AM" src="https://github.com/user-attachments/assets/8c504da1-e76b-4136-ba24-1d5f03bea3e3">| <img width="973" alt="Screenshot 2024-07-15 at 11 08 45 AM" src="https://github.com/user-attachments/assets/aabbe7c2-254c-4575-9b58-bbad543a4111">|
|<img width="952" alt="Screenshot 2024-07-15 at 11 08 54 AM" src="https://github.com/user-attachments/assets/ad4e8c94-13aa-46f2-b388-d7151677076f"> |<img width="950" alt="Screenshot 2024-07-15 at 11 08 58 AM" src="https://github.com/user-attachments/assets/d03d786e-85d8-44ff-a615-0dc1e3cd2744">|
I noticed today during the demo that `developer-framework` folder in the directory reference should actually just be `developer`, so I fixed that.
I removed the …
=> Fiddled with callout & link padding, edited README

site/_quarto.yml, site/developer/model-testing/test-sandbox.qmd
> For sc-5541, I discovered this is actually just a limitation of mobile popovers: https://stackoverflow.com/questions/64618889/fontawesome-icons-showing-on-desktop-but-not-on-mobile
- None of the alternative icon extensions offered by Quarto resolved this issue (they all used the `@font-family` css) 
- So I removed the icon from that page's title and modified the navigation link to match the other entries in the Developer Framework dropdown (and now everything is AOK on mobile)
| Page & navigation drop-down | Mobile view|
|---|---|
| <img width="1726" alt="Screenshot 2024-07-31 at 3 52 18 PM" src="https://github.com/user-attachments/assets/8f1f6427-76e1-48e1-b91d-ed65e383f6f8">| <img width="402" alt="Screenshot 2024-07-31 at 3 55 55 PM" …
=> Removed icon from .qmd title and added it to navigation link

.github/workflows/ai_explain.py, .github/workflows/ai_explain.yaml
Context: https://validmind.slack.com/archives/C06JS5D1DNV/p1723151422066149
=> Added ai_explain

site/Makefile
There was an issue with some dependencies not being installed within the cloned little folder of the developer-framework repo. 
By adding `make install` to the Makefile, dependencies are installed and the scripts can run normally.
=> Added `make install` to the Makefile to install dependencies

site/developer/model-documentation/generate-model-documentation.qmd, site/faq/faq-documentation.qmd
> For sc-6033, I added a quick reference to the Documentation FAQ and linked to it in `/developer/model-documentation/generate-model-documentation.qmd`
| Old | New |
|---|---|
| <img width="1626" alt="Screenshot 2024-08-21 at 12 10 17 PM" src="https://github.com/user-attachments/assets/eada5880-4ec6-4ceb-bf25-370746874a10"> | <img width="1525" alt="Screenshot 2024-08-21 at 12 04 43 PM" src="https://github.com/user-attachments/assets/973007cf-e2b8-418d-b02f-6bee9863eef9">|
| Old | New |
|---|---|
| <img width="1668" alt="Screenshot 2024-08-21 at 12 10 07 PM" src="https://github.com/user-attachments/assets/974c7bc0-e048-49c9-8c24-f77e0bc172df"> | <img width="1713" alt="Screenshot 2024-08-21 at 12 04 22 PM" src="https://github.com/user-attachments/assets/c7edd96f-7136-49b4-91d4-897ff8e36634"> …
=> Added some references for loading model predictions w/o available model

.github/workflows/delete-pr-preview.yaml, .github/workflows/deploy-docs-prod.yaml, .github/workflows/validate-docs-site.yaml, README.md
This PR adds automatic previews that 
- get deployed to our docs-demo site when you create or update a PR; AND 
- get deleted when the PR gets merged or closed
In our docs CI/CD deployment proposal, this PR adds the following highlight:
Successful run: https://github.com/validmind/documentation/actions/runs/10673952942
Successful run https://github.com/validmind/documentation/actions/runs/10674028315
We already had a check to render the docs site and run tests. Together with a bit of editing of the existing workflow, we now basically take the output of that `quarto render` step and sync it to AWS S3, making it an efficient solution to deploy PR previews. 
**Why not a separate workflow to deploy PR previews?** The existing quarto render CI check gives us everything we need and is also the …
=> Add PR previews

.github/workflows/ai_explain.yaml
> @cachafla The PR Review bot is neat but runs way too often for us. I've adjusted it (hopefully) to only run the once when a PR has a review requested based on these docs: [GitHub — Events that trigger workflows (pull_request)]( https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request)
cc @nrichers for visibility.
=> Only running the PR previews bot when a PR is ready for review

.github/workflows/validate-docs-site.yaml, site/developer/model-testing/test-descriptions.qmd
This PR modifies our test description wildcard embeds from `**` to `*.md` to resolve duplicated but blank tiles.
| Before — [docs.validmind.ai](https://docs.validmind.ai/developer/model-testing/test-descriptions.html) | After —  [Preview URL](https://docs-demo.vm.validmind.ai/pr_previews/nrichers/sc-6331/investigate-listing-page-issue-for-test-descriptions/developer/model-testing/test-descriptions.html) |
|--------|--------|
| <img width="1440" alt="image" src="https://github.com/user-attachments/assets/69c8e6e1-b60d-4ed0-b611-05bc0a87a242"> | <img width="1440" alt="image" src="https://github.com/user-attachments/assets/938cbe9a-5f05-4122-ade8-b2103f3f02de"> |
Note this change seems to work just fine for subdirectories.
During testing on a local Linux container, the site rendered just …
=> Investigate listing page issue 

.github/workflows/deploy-docs-prod.yaml, .github/workflows/deploy-docs-staging.yaml
This PR adds a trigger to workflows that deploy our docs sites to staging and prod. Specifically, these workflows now also trigger when the workflows to merge into these branches have completed. This change is required to 
(Note the workflow to merge staging into prod doesn't exist, yet. This is for future me who would otherwise be puzzled why deployment doesn't trigger when we try to automate. If you trace it back to this PR — you're welcome.)
=> Update workflows to trigger on workflow_run

site/guide/model-documentation/work-with-content-blocks.qmd, site/guide/model-inventory/edit-model-inventory-fields.qmd, site/guide/model-inventory/manage-model-inventory-fields.qmd, site/guide/model-validation/add-manage-model-findings.qmd
> sc-6602
Confirmed that we are only adding the model inventory field type to models at the moment, not present on documentation/reports/workflows/etc.
**Manage model inventory fields:** [LINK](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-6602/documentation-user-should-be-able-to-define/guide/model-inventory/manage-model-inventory-fields.html#inventory-field-types)
**Edit model inventory fields:** [LINK](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-6602/documentation-user-should-be-able-to-define/guide/model-inventory/edit-model-inventory-fields.html#manage-supporting-documentation)
=> Added attachment field type

site/training/training.qmd
> sc-6684
I added two new aliases to `training.qmd`:
- `index.html`
- `training-overview.html`
I tested these redirects locally and they work! Neat Quarto feature, we can probably use the alias tool for some of our other renamed docs as well just for fallback's sake.
- **`index.html`:** https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-6684/create-redirect-for-docs-validmind-ai-training/training/index.html
- **`training-overview.html`:** https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-6684/create-redirect-for-docs-validmind-ai-training/training/training-overview.html
=> Added new aliases to `training.qmd`

site/developer/samples-jupyter-notebooks.qmd
This PR adds a link to our open-source repo on GitHub:
LIVE PREVIEW
We added a link to our open-source software on GitHub to the code samples page. [Try it on GitHub](https://github.com/validmind/developer-framework)
=> Add link to GitHub for code samples

site/styles.css
> sc-6988
It was all my bad, I added some janky margin padding to the footer when I should have added it to the index-locked releases div. Should be good now: [**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-6988/investigate-janky-footer-footnotes-styling/index.html)
=>  Resolved janky footer styling

site/_extensions/nrichers/preview/preview.css, site/about/contributing/style-guide/conventions.qmd, site/index.qmd, site/styles.css, site/training/administrator-fundamentals-register.qmd, site/training/training.qmd
Cleaned up the neat training edits Nik set up!
[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/training-adjusts/index.html)
Just made sure the admin training was all in one line:
Added the author & reading time to the notebooks:
=> Adjusting training styles

site/training/assets/training.css
I noticed during the demo video that was filmed the BG img for the training hero banner repeats instead of being seamless. Fixed now.
| Old | New |
|---|---|
| <img width="1710" alt="Screenshot 2024-11-12 at 2 06 04 PM" src="https://github.com/user-attachments/assets/ca262a1a-1718-4f8b-a668-0fd675153ae0"> | <img width="1708" alt="Screenshot 2024-11-12 at 2 06 28 PM" src="https://github.com/user-attachments/assets/58171f3c-d9f8-407e-8bf6-0778d150ba1b">|
=> Quick adjustment to hero BG img for training 

site/about/contributing/style-guide/conventions.qmd, site/releases/2024-oct-22/release-notes.qmd, site/styles.css, site/training/training.qmd
- Reverted the `training/training.qmd` (training landing page) top nav to white for contrast with the special hero banner
- Fixed the disappearing footer hover links
- Adjusted the video border convention
| Old | New |
|---|---|
| <img width="1711" alt="Screenshot 2024-11-18 at 10 04 59 AM" src="https://github.com/user-attachments/assets/329545f3-430b-45f5-993c-af2e8564ef62">| <img width="1710" alt="Screenshot 2024-11-18 at 10 25 15 AM" src="https://github.com/user-attachments/assets/cefb9a10-0485-4aaf-9029-d3f06b0c674f">|
|<img width="1710" alt="Screenshot 2024-11-18 at 10 05 11 AM" src="https://github.com/user-attachments/assets/506b2d16-5bfb-4aef-b666-0cd6786dcd67"> |<img width="1710" alt="Screenshot 2024-11-18 at 10 25 26 AM" …
=> Quick CSS cleanup

site/guide/model-inventory/archive-delete-models.qmd
Riffing on https://github.com/validmind/documentation/pull/537!
> [**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/pr%23537-suggestions/guide/model-inventory/archive-delete-models.html)
This was already on the article, it links to our permissions guide:
Updated the verbiage here to call out that you can reactivate, footnote just links to the subsequent section:
Updated the footnotes here as they were shifted to accommodate for the additional one added in the above section:
=> Making changes for Mehdi :)

site/_quarto.yml, site/guide/configuration/log-in-to-validmind.qmd, site/styles.css, site/training/assets/training.css
This PR adds a **Login** button & menu to our docs site. If this format works for you, we can ask CSTMR to add the same button to our main site: [**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/nrichers/sc-7484/add-login-button-to-docs-site/index.html)
As part of this change, I'm also switching the search over to the navbar icon — it helps with spacing for the Login button and helps differentiate how search on the front page is subtly different from search that is available elsewhere. 
How it works: 
We added the option to log in to the ValidMind Platform to our docs site, making it easy for you to find the right login. Click **Login** to try it out.
=> Add login button to docs site

.github/workflows/deploy-docs-prod.yaml, .github/workflows/deploy-docs-staging.yaml, .github/workflows/validate-docs-site.yaml, site/_quarto.yml, site/notebooks/README.md
Refer to https://github.com/validmind/documentation/pull/552:
> I think I know why the comparison is failing — our branches essentially match between merges, so we actually have to compare the PR being merged to the base instead
1. - [x] Initial PR creation will NOT trigger the notebook execution: [**SUCCESSFUL WORKFLOW RUN**](https://github.com/validmind/documentation/actions/runs/12075894036/job/33676434071?pr=554)
2. - [x] `site/notebooks/**` has a change pushed up to the PR, it will trigger the notebook execution: [**SUCCESSFUL WORKFLOW RUN**](https://github.com/validmind/documentation/actions/runs/12077048656/job/33679352389?pr=554)
=> Quick workflow filter tweak

.github/workflows/deploy-docs-prod.yaml, .github/workflows/deploy-docs-staging.yaml, .github/workflows/validate-docs-site.yaml, site/notebooks/README.md
I THINK I finally refined it to the point where it will work. Some of the issue was the previous set-up defaults to always checking against `main` because that is the behaviour of how `${{ github.head_ref }}` works:
- Only available in the context of a PR and not a workflow push (So for example, when I tried to hack the deploy staging & docs workflows further because those are triggered by the `merge-x-into-...` workflows it ignored the input) 
- Always checks against the branch the PR was created from (in this case, `main`) even if you specify a different `base`
Now this checks the current PR against the branch you're intending to merge into (so it will in theory also work when we preview the site for pushes to `prod` and not just working PRs pre-`main` merge 🤞🏻):
```
- name: Filter …
```
=> Fixing on the fly notebook execution filter

.github/workflows/deploy-docs-prod.yaml, .github/workflows/deploy-docs-staging.yaml
[Apparently the workflows don't like `origin/{branch}`](https://github.com/validmind/documentation/actions/runs/12147361786/job/33873963795)... SO I am trying ONE MORE THING, and if this doesn't work @nrichers you might have to take over. Stupid workflows. 
Ensuring we fetch all the branches when we check out the repo:
```
- name: Check out repository
uses: actions/checkout@v2
with:
fetch-depth: 0  # Fetch all branches
```
Just using `staging` as `base` instead of `origin/staging`:
```
- name: Filter changed files
if: ${{ steps.fetch_staging.outcome == 'success' }}
uses: dorny/paths-filter@v2
id: filter
with:
base: staging
ref: ${{ github.sha }}
filters: |
notebooks:
- 'site/notebooks/**'
```
**To reiterate, the issue isn't the heap tracking/execution profiles, it's filtering for changed …
=> Filtering for changes on prod/staging

.github/workflows/deploy-docs-prod.yaml, .github/workflows/deploy-docs-staging.yaml, site/notebooks/README.md
I keep saying I'm giving up but then I don't... anyway. 
The LAST attempt gave me some interesting info in the logs. It did properly check against the correct `base` (`staging`) with the current commit aligning to the PR branch that was being merged in, but it still told me there was no difference in files:
Presumably because when the `merge-main-into-staging.yaml` workflow is complete, there ARE no changes in between `staging` and the commit being compared, because it's already been smushed in...
And so, I am trying to explicitly call the commit PRIOR to the most recent commit:
```yaml
- name: Filter changed files
if: ${{ steps.fetch_staging.outcome == 'success' }}
uses: dorny/paths-filter@v2
id: filter
with:
base: staging~1
ref: ${{ github.sha }}
filters: |
notebooks:
- …
```
=> Live notebook execution workflows, take ... whatever

.github/workflows/deploy-docs-prod.yaml, .github/workflows/deploy-docs-staging.yaml, site/notebooks/README.md
ohmygawddd i hate that you can't just test a workflow locally firstttt
[Turns out it hates the `~1`.](https://github.com/validmind/documentation/actions/runs/12168046796/job/33937973632) The weird thing is, the FIRST execution of the staging filter found changed files, without extra parameters, but I DON'T UNDERSTAND WHY IT WORKED. 💀 [Especially since I just inspected that workflow and it's checking the files against `main`.](https://github.com/validmind/documentation/actions/runs/12021785963/job/33512891350) ????
I just noticed this in the docs though, which is slightly different than what I tried before (previously I tried `${{ github.head_ref }}`):
=> Execution workflows are driving Beck insane

.github/workflows/deploy-docs-prod.yaml, .github/workflows/deploy-docs-staging.yaml
Yeah, I gave up and just removed the filter for changed files on the `staging` and `prod` workflows. 
Here's the follow-up story in case you want to take a stab at it, @nrichers: https://app.shortcut.com/validmind/story/7680/have-staging-prod-workflows-filter-so-that-they-only-execute-notebooks-when-notebooks-are-changed
=> Removing the workflow filters for staging & prod

site/about/glossary/_models.qmd
Kevin pointed out this link to SR 11-7 in our glossary is broken, now fixed. 
EDIT: Did a quick search through the repo and this looks to be the only occurrence of this particular malformed link.
=> Fix link to SR 11-7

site/_quarto.yml
Forgot the guides link in the documentation drop-down. Fixed. 🤦🏻 
| Before | After |
|---|---|
|<img width="304" alt="Screenshot 2024-12-12 at 1 05 59 PM" src="https://github.com/user-attachments/assets/189c42dd-cbd2-4713-98f9-8cc2bffdac10" /> | <img width="308" alt="Screenshot 2024-12-12 at 1 03 26 PM" src="https://github.com/user-attachments/assets/257b31af-77ee-4a0b-abb1-65bb1df02399" />|
=> Forgot the guides in the dropdown

site/_quarto.yml, site/about/overview-model-documentation.qmd, site/developer/get-started-validmind-library.qmd, site/developer/model-documentation/install-and-initialize-validmind-library.qmd, site/developer/model-documentation/supported-models.qmd, site/developer/model-testing/test-descriptions.qmd, site/developer/model-testing/test-sandbox.qmd, site/developer/model-testing/testing-overview.qmd, site/developer/samples-jupyter-notebooks.qmd, site/get-started/get-started.qmd, site/releases/2024-jun-10/release-notes.qmd
> sc-6526
Realised I used the same icon for "Guides" and "About" when I fixed this, so:
| Old | New |
|---|---|
|<img width="275" alt="Screenshot 2024-12-16 at 12 59 58 PM" src="https://github.com/user-attachments/assets/ca918c71-c620-48de-982b-287c950e885b" />|<img width="288" alt="Screenshot 2024-12-16 at 1 11 26 PM" src="https://github.com/user-attachments/assets/59075c76-3156-40bb-94f9-88ad933d8a60" /> |
[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-6526/docs-audit-p3-developer-framework/developer/get-started-validmind-library.html)
Just some quick visual cleanup, made sure any images had alt-text & captions, etc. as we are likely going to make more notable edits when we restructure our docs. 
| Old | New |
|---|---|
|<img width="1187" alt="Screenshot …
=> Docs quick audit — ValidMind Library

Dockerfile, README.md, site/Makefile
For self-hosted installations, we agreed to create a Docker image that can be shipped with the rest of the product. This PR adds:
- `Dockerfile` — Uses the rendered site output in `site/_site` and turns it into a Docker image that can be served on port 4444
- `make docker-image`— Renders the docs site, builds the image, and serves it locally for testing
- `README.md` — Explains the above
I also updated the mostly unused `docs-site` action to use our production profile. We don't use this action as part of our workflow generally, so it should be fine to repurpose for the Docker image. 
Relevant bits from `make docker-image`:
```
Building the Docker image ...
[+] Building 2.9s (7/7) FINISHED …
```
=> Add Docker image for our docs site

site/about/overview-llm-features.qmd, site/releases/2023/2023-aug-15/highlights.qmd
https://github.com/validmind/documentation/pull/605
=> Resolving publication conflicts for PR#605

site/Makefile
This PR executes the notebook we use for our developer fundamentals training course as part of ~building the Docker image of our~ rendering our docs site.
EDIT: I moved the execute action into the docs-site action rather than calling it when building the Docker image. This means that rendering the docs site locally always executes the notebook rather than only when building the Docker image. I think that approach makes more sense logically since rendering the docs site should, well, render the (complete) docs site. 
Fixes: [sc-7834](https://app.shortcut.com/validmind/story/7834/do-docker-images-need-to-run-make-execute-when-they-get-built)
JavaScript widgets show up, e.g.:
Notable stuff:
- Uses the correct profile for production — `quarto render --profile exe-prod …
=> Add make execute PROFILE=exe-prod to docs-site action 

site/_quarto.yml, site/guide/model-inventory/customize-model-inventory-layout.qmd, site/guide/model-inventory/customize-model-overview-page.qmd, site/guide/model-inventory/edit-model-inventory-fields.qmd, site/guide/model-inventory/register-models-in-inventory.qmd, site/guide/model-inventory/working-with-model-inventory.qmd
> sc-4752
Net-new page: [**LIVE PREVEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-4752/documentation-implement-customizable-model/guide/model-inventory/customize-model-overview-page.html)
Added under the "Working with the model inventory umbrella": [**LIVE PREVEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-4752/documentation-implement-customizable-model/guide/model-inventory/working-with-model-inventory.html)
=> Docs — Customize model overview page

site/guide/model-inventory/manage-model-inventory-fields.qmd, site/guide/model-workflows/set-up-model-workflows.qmd
> sc-7615
**[LIVE PREVIEW](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7615/documentation-support-for-wait-steps/guide/model-inventory/manage-model-inventory-fields.html#inventory-field-types)**
Added some clarification on timezone/displays under `Inventory field types` for these fields as they were missing before.
**[LIVE PREVIEW](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7615/documentation-support-for-wait-steps/guide/model-workflows/set-up-model-workflows.html#wait)**
New `Wait` step under `Available step types`:
=> Added instructions for Wait steps in workflows

site/releases/2025/2025-jan-31/release-notes.qmd
Small fix for a broken link I noticed in our Jan 31 release notes
=> Fix notebook link

.github/pull_request_template.md, release-scripts/generate-release-notes.ipynb, release-scripts/generate_release_objects.py, site/releases/2024/2024-jan-26/highlights.qmd, site/releases/breaking-changes/README.md
> sc-8459
Added to:
- [`documentation`](https://github.com/validmind/documentation/issues/labels)
- [`validmind-library`](https://github.com/validmind/validmind-library/issues/labels)
- [`frontend`](https://github.com/validmind/frontend/issues/labels)
Added the instructions for the `breaking-change` label to:
- `documentation`: 
https://github.com/validmind/documentation/blob/61a07ecc5d27e274733f0bacbe5305c869667e07/.github/pull_request_template.md?plain=1#L11
- `validmind-library`: https://github.com/validmind/validmind-library/pull/318
- `frontend`: https://github.com/validmind/frontend/pull/1234
Updated both of these to include the `breaking-change` > `## Breaking changes` label to header in the hierarchy:
Setting up the object for the categories based on PR labels: …
=> + `breaking-change` releases tag, PR template, & release script update

.github/workflows/test_installation_trigger.yaml
Just an example of how we can trigger a workflow in another repository via repository dispatch. The purpose of this PR is to test triggering another workflow in the `installation` repo to deploy an instance of our docs site with additional content.
=> feat: example implementation of trigger in other repo

site/Makefile
This PR removes one of those 'we should fix this some day' annoyances that I've spent more time explaining in the last week than it would take to fix. This PR fixes THE LAST PIECE in the puzzle. 
**Before**
We had an extra docs site in the root of the `s3://docs-ci-cd-demo` bucket that goes back to the very early days of Andres and I experimenting with docs deployment. This site serves no purpose, is not current, and is not used — other than we need in index.html in the root of `origin/` for the PR previews to work. 
You could deploy this site with `make deploy-demo`. 
**After**
This site has now been deleted, replaced with an index.html that redirects to https://docs-staging.validmind.ai/ if you try to access the root of `origin/`. Eventually, we might want to list all the PR previews …
=> Remove defunct deploy-demo make action

.github/workflows/deploy-docs-prod.yaml, .github/workflows/validate-docs-site.yaml, .gitignore, site/Makefile, site/_quarto.yml, test_results.md
To enable @nibalizer, we need to cherry pick 9f62f0732635a2617241fab20908a94ffe4c1a37 from #677 into `prod`.
=> Cherry pick #677 into `prod`

site/Makefile
This PR enables cloning the validmind-library at a specific release tag to ensure version-accurate documentation for:
- Notebooks with code samples
- Generated Quarto Markdown for our Python API reference
- Test descriptions generated on the fly
The detached HEAD state is expected — we are checking out a specific SHA rather than tracking the latest commit (which is HEAD)
**Important:** It’s safe to run `make get-source` to test the changes, but do not commit the output yet.
Our docs site now relies on the generated Quarto Markdown for the Python API reference. To avoid breaking the documentation, we must wait for a new release tag in the `validmind-library` repository that includes this Quarto Markdown before committing the cloned source.
=> Enable cloning at a specific release tag

site/_extensions/gadenbuie/now/_extension.yml, site/_extensions/gadenbuie/now/now.lua, site/_quarto.yml, site/about/fine-print/data-privacy-policy.qmd, site/about/fine-print/license-agreement.qmd, site/about/overview-llm-features.qmd
This PR updates our site footer & license agreement to automatically use the current year, which is what our main site uses, and fixes some links to our main site for the legal fine print. 
@mehdi0501 FYI
**Before**
**After**
Now also uses the current year automatically: 
These links were broken, now fixed: 
Our data privacy topic now includes a new section that links users to the “Legal Ease” on our main site:
Our LLM features topic had a preview to the "Legal Ease" that was broken, simplified with a new listing tile that contains the link:
=> Automatically set the year in footer & fix links to main site

site/_quarto.yml, site/about/overview-model-risk-management.qmd, site/faq/faq-documentation.qmd, site/faq/faq-reporting.qmd, site/guide/guides.qmd, site/guide/model-documentation/export-documentation.qmd, site/guide/model-validation/working-with-model-findings.qmd, site/guide/reporting/export-documentation.qmd, site/releases/2023/release-notes-2023-may-30.qmd, site/releases/2025/2025-mar-07/release-notes.qmd
This PR adds the missing steps for exporting ongoing monitoring documentation:
Story details: https://app.shortcut.com/validmind/story/9632
=> fix: [sc-9632] Add missing "Export ongoing monitoring document" section to docs

site/_quarto-exe-demo.yml, site/_quarto-exe-prod.yml, site/_quarto-exe-staging.yml
The latest version of Quarto breaks our existing notebook execution workflow, as it fixed a workaround dependency with the `jupyter-widgets` package:
```bash
FATAL (/opt/quarto/share/filters/main.lua:3977) An error occurred:
Error resolving include-after- unable to open file https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js
```
> **[Broken workflow run](https://github.com/validmind/documentation/actions/runs/14936423749/job/41964785160?pr=712)** — Attached to this attempt to merge `staging` to `prod` last week: https://github.com/validmind/documentation/pull/712
Removing this explicit embed from the execution profiles solves the issue in my testing:
```yaml
include-after-body: 
- https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js
```
> **[Fixed workflow …
=> hotfix: -`include-after-body` in execution profiles

site/faq/faq-testing.qmd
Updated the FAQ section. We added testing scenarios for Developers and Validators about how to log tests.
**New**
You can take a look at the git diffs:
Pull down this PR: gh pr checkout 722
1- Open **documentation/site/faq/faq-testing.qmd** 
2- Call **cd site** in your terminal to navigate into the site directory where our docs site files live.
3- Call **quarto preview** to pull up a live version of the changed site.
=> Edited the FAQ testing file (faq-testing.qmd). Added 2 new sections.

.github/workflows/deploy-docs-prod.yaml, .github/workflows/deploy-docs-staging.yaml
I forgot to remove the conditional steps for the staging and production workflows, which affected the execution for the notebooks out to staging and prod:
- [Staging workflow](https://github.com/validmind/documentation/actions/runs/15169920006/job/42657142575)
- [Production workflow](https://github.com/validmind/documentation/actions/runs/15174567966/job/42672177641)
I've removed the conditionals for a step that doesn't actually exist, and now staging and production should always execute the training notebooks as expected.
=> infra: Remove conditional execution for staging and prod

site/training/program/training-faq.qmd
https://app.shortcut.com/validmind/story/10752/fix-links-in-training-faq
I changed the HTML links in our page to QMD files.
Some buttons (both training and docs) are linked to the same pages (not sure if it was intended)
Since the online preview won't display the notebook iFrames correctly (it pulls the relative link from the root of the docs-demo repo rather than the PR branch):
1. Grab this PR: gh pr checkout 747
2. Make sure you're in the site directory if you're not already: cd site
3. Pull up a live preview: quarto preview
Review the training FAQ homepage (you might need to add the path of it right after preview to access it easily)
=> Fix links in training faq

site/guide/_sidebar.yaml, site/guide/model-inventory/_add-edit-inventory-fields.qmd, site/guide/model-inventory/manage-model-inventory-fields.qmd, site/guide/model-validation/manage-model-finding-fields.qmd, site/guide/model-validation/managing-model-validation.qmd
> sc-11050
We can now add custom findings fields, which needs documentation.
](https://docs.validmind.ai/guide/model-validation/view-filter-model-findings.html#customize-model-findings-layout)
Release notes should be covered in the feature release https://github.com/validmind/frontend/pull/1506.
=> docs: Manage model finding fields

site/guide/model-workflows/_review-active-workflows.qmd
> sc-11176
Notes submitted during workflow transitions are now tracked in the workflow activity panel. Docs have been updated to accommodate this change.
Click on the LIVE PREVIEW and confirm the changes in the screencaps below: [**Manage model workflows**](https://docs-staging.validmind.ai/pr_previews/beck/sc-11176/documentation-updates-for-user-action-step/guide/model-workflows/manage-model-workflows.html#review-active-workflows)
| Updated section | Additional footnote |
|--|--|
|<img width="1239" height="664" alt="Screenshot 2025-08-01 at 11 10 48 AM" src="https://github.com/user-attachments/assets/d53ac14b-6394-438f-ba06-db775e3acb12" /> | <img width="1259" height="672" alt="Screenshot 2025-08-01 at 11 10 58 AM" src="https://github.com/user-attachments/assets/6109215a-5d0d-4cfc-8ba2-85 …
=> docs: Notes tracked on workflow transitions

.github/workflows/validate-docs-site.yaml, site/_quarto-exe-demo.yml, site/notebooks/EXECUTED/test.ipynb
> sc-11680
https://github.com/validmind/documentation/pull/878 broke our PR preview when notebooks were included in the render (executed) as the output for some of the cells throw some `WARNINGS` that don't actually affect the final display of the page; they've been there since implementation.
I moved the test for errors/warn/warnings etc. step to BEFORE the notebook execution to sidestep this issue.
Compare the workflow that was unsuccessful: https://github.com/validmind/documentation/actions/runs/16809938498
With the workflow that succeeds: https://github.com/validmind/documentation/actions/runs/16812671505/job/47621652045?pr=884
I merged this without review because we needed to get these patch release notes out on production and I needed to make sure the push to prod looked OK: …
=> Workaround for Quarto render WARNING testing for notebook execution

README.md, site/css/_bug-fixes.css, site/css/_codeblocks.css, site/guide/monitoring/set-thresholds-and-alerts.qmd, site/styles.css
This PR:
- Fixes the codeblock formatting issue when a language is specified to highlight syntax
- Puts the bug fix and CSS for codeblocks into modular CSS files
| Source | Output BEFORE | Output AFTER |
|--------|--------|-------|
|  <img width="300" height="439" alt="Capto_ 2025-08-19_04-20-37_pm2" src="https://github.com/user-attachments/assets/e8cebf96-e60f-4d03-8b3e-019a9d1bad04" /> | <img width="269" height="333" alt="Capto_ 2025-08-19_04-10-56_pm2" src="https://github.com/user-attachments/assets/908aee01-fdbe-415f-a910-44ce252fce81" /> | <img width="269" height="333" alt="Capto_ 2025-08-19_04-11-14_pm" src="https://github.com/user-attachments/assets/6f171a1b-8ad2-4a38-9913-2b706cb591f8" /> |
Relates to [sc-11359](https://app.shortcut.com/validmind/story/11359/investigate-python-code …
=> Fix codeblock formatting issue and import as modular CSS

site/_quarto-development.yml, site/_quarto-production.yml, site/_quarto-staging.yml, site/_quarto.yml, site/_variables.yml, site/developer/developer.css, site/guide/access/log-in-to-validmind.qmd, site/styles.css, site/training/assets/training.css
This PR:
- **Removes the "Log In" menu from the Docker image**: Because the information was specific to our environment and we do not know where customers deploy to, the menu has been removed globally.
- **Updates the "Log in to ValidMind" topic for the Docker image**: We now include guidance on supporting intranet URLs and points to where more details can be found. We can't be too specific here but we can include enough information to be helpful.  
Our public docs site remains unchanged.
Relates to [sc-11817](https://app.shortcut.com/validmind/story/11817/address-docs-login-to-directing-to-validmind-on-prod-instance-179)
**Removed "Log In" menu**
| Before | After |
|---------------------|--------------------|
| <img width="1216" height="389" alt="Capto_ 2025-08-19_12-19-25_pm" …
=> Nrichers/sc 11817/address docs login to directing to validmind

site/_variables.yml
> sc-7174
We now pull in the production library version in the Python API docs, and don't reference the library version elsewhere. Removing the variable to reduce confusion/accidental usage.
(I considered populating the variable in the `_variables.yml` file with a script from the source, but we don't even use the variable anywhere for that much work to be put into that workaround . . .
n/a
n/a
n/a
n/a
=> Removing validmind version variable

site/guide/_sidebar.yaml, site/guide/guides.qmd, site/guide/reporting/export-documents.qmd, site/guide/reporting/export-findings.qmd, site/guide/reporting/export-inventory.qmd, site/guide/reporting/generating-exports.qmd, site/releases/2025/2025-jan-31/release-notes.qmd
> sc-12117
We were missing information on how to export the list of models in the inventory as this feature is now available on production.
Click the LIVE PREVIEW: [**Export inventory**](https://docs-staging.validmind.ai/pr_previews/beck/sc-12117/add-export-model-inventory-topic/guide/reporting/export-inventory.html)
- I also added a new high-level topic for exporting: [**Generating exports**](https://docs-staging.validmind.ai/pr_previews/beck/sc-12117/add-export-model-inventory-topic/guide/reporting/generating-exports.html)
- Listing tile on guides has been updated as well: [**Guides > Reporting**](https://docs-staging.validmind.ai/pr_previews/beck/sc-12117/add-export-model-inventory-topic/guide/guides.html#reporting)
n/a
You can now export lists of models tracked in the {{< var …
=> docs: Export inventory
