- site/guide/get-started.qmd
> Update get-started.qmd to fix typo

- site/_quarto.yml
Love our new banner! Here's some small text tweaks I'd like to suggest: 
- Group like things together to reduce segmentation ('gain hands-on experience & training env' go closely together)
- End the text cleanly with the main CTA ('explore what VM has to offer')
- Remove period at the end as banners typically shouldn't have one, similar to UI toasts 
EDIT: An even simpler banner would be "**Try our training environment to explore what ValidMind has to offer**" — what do you think?
EDIT EDIT: I'm gonna push a commit for the even simpler banner.
> Update site banner

- site/developer/get-started-developer-framework.qmd
I THOUGHT this was edited in your PR Nik, but I think my eyes are just playing tricks on me. No push to prod tonight 💀 
Ref: https://github.com/validmind/developer-framework/blob/main/notebooks/code_samples/customization/customizing_tests_with_output_templates.ipynb
Quarto Render didn't seem to catch if this broke any other links, but I suppose we'll find out.
> customizing_metrics_with_output_templates.ipynb > customizing_tests_with_output_templates.ipynb

- README.md
> Test staging > prod PR#373

- site/Makefile
While fixing the merge conflicts in Beck's PR I noticed that the Makefile had some changes in it from testing that needed to fixed. This PR does just that.
> Fix staging deploy in Makefile

- README.md
This is a test PR to check if merging into `staging` works.
> Testing simplified merge strategy

- .github/workflows/merge-main-into-staging.yaml
This PR fixes a test change that I forgot to undo.
> Fix branch in merge-main-into-staging.yaml

- site/guide/guides.qmd
This PR embeds the playlist for "Validating Models 101" into our Guides landing page. This playlist includes five short videos, re-recorded with higher production quality, that cover:
- Intro & quick tour for validators
- Review model documentation
- Analyze test results
- Prepare validation report
- Submit for review & approval
[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/nrichers/sc-6631/re-record-validating-models-101-videos/guide/guides.html#model-validation)
We created a series of short videos that introduce you to validating models on our platform. [Watch the video series ...](../../guide/guides.html#model-validation)
> Embed Validating Models 101 playlist into Guides section

- site/developer/model-testing/testing-overview.qmd
This PR adds a new "How do I ... add tests?" FAQ-style video to our developer content. This is a single, short FAQ-style video that answers a specific question. This one covers:
- Exploring tests
- Using ValidMind to filter for tests
- Adding tests to your model documentation
[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/nrichers/sc-6095/how-to-video-for-run-tests/developer/model-testing/testing-overview.html#explore-tests-and-test-suites)
Note this video embed does not include lead-in text. Some had been added to https://github.com/validmind/documentation/pull/446 but I removed it again for the sake of simplicity. 
(Related, I am not clear on what alt tests we might need to provide for videos. YouTube does generate captions but it's something to look into.)
We added a …
> Embed "How do I ... add tests?" video in developer docs

- .github/workflows/deploy-docs-prod.yaml
- .github/workflows/deploy-docs-staging.yaml
- site/notebooks/README.md
OK, https://github.com/validmind/documentation/pull/559 didn't work — still checking against `main` since that's what the originating commit that is being pushed came from.
I am trying this ONE LAST THING, which is explicitly fetching the `base` branch and calling that instead of relying on the `${{ github.event.before }}` variable. If this doesn't work, then yes, I give up. 
```yaml
- name: Fetch staging branch
id: fetch_staging
run: git fetch origin staging
- name: Filter changed files
if: ${{ steps.fetch_staging.outcome == 'success' }}
uses: dorny/paths-filter@v2
id: filter
with:
base: origin/staging
ref: ${{ github.sha }}
filters: |
notebooks:
- 'site/notebooks/**'
```
```yaml
- name: Fetch prod branch
id: fetch_prod
run: git fetch origin prod
- name: Filter changed files
if: ${{ …
```
> 1 last attempt at the execution workflows

- site/training/administrator-fundamentals/administrator-fundamentals-register.qmd
- site/training/administrator-fundamentals/administrator-fundamentals.qmd
- site/training/developer-fundamentals/developer-fundamentals-register.qmd
- site/training/developer-fundamentals/developer-fundamentals.qmd
- site/training/validator-fundamentals/validator-fundamentals-register.qmd
- site/training/validator-fundamentals/validator-fundamentals.qmd
> sc-7476
[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7476/developer-fundamentals-training-needs-a-better/training/developer-fundamentals/developer-fundamentals-register.html) — **REMINDER THAT THE NOTEBOOK EMBEDDED IN THE TRAINING IFRAME IS GOING TO PULL FROM THE ROOT OUTDATE DOCS-DEMO NOTEBOOK FOLDER AND NOT THE UPDATED PR FOLDER IN THE PREVIEW. PREVIEWING LOCALLY WILL NOT HAVE THE EXECUTION OUTPUT, BUT WILL BE MORE ACCURATE IN TERMS OF ANCHOR SECTIONS.**
- Added the `Train a model` section into PART 2
- Split this course into 3 as with the additional section it's very long — added 10 minutes to the overall course time to accommodate these extra cells being run as well
- The "1. Initializing the ValidMind Library" iframe was still linking to the old …
> Cleaned up Developer Fundamentals & other training

- test-results/.last-run.json
This PR removes some stray files I accidentally created and then committed while testing.
> Delete test-results directory

- site/faq/faq-workflows.qmd
> Missing footnote from FAQ

- site/guide/model-documentation/export-documentation.qmd
> sc-8289
Updated this quickly for the new validation report options:
| OLD | NEW |
|---|---|
|<img width="1307" alt="Screenshot 2025-01-29 at 2 14 05 PM" src="https://github.com/user-attachments/assets/40e6f960-a633-4b79-84d5-fa462479c59e" /><img width="1261" alt="Screenshot 2025-01-29 at 2 14 20 PM" src="https://github.com/user-attachments/assets/204600f0-93c9-4a86-aaa0-ad206bf8adc2" /> | <img width="1255" alt="Screenshot 2025-01-29 at 2 15 56 PM" src="https://github.com/user-attachments/assets/731fa24f-2e47-4ae9-868a-b2b133191de4" /><img width="1255" alt="Screenshot 2025-01-29 at 2 16 03 PM" src="https://github.com/user-attachments/assets/5f11860a-334b-4645-bb34-0b837168b599" /> |
> Edits to Export documentation for validation reports

- site/Makefile
The issue is I've never been able to do the jupyter builds. We can make this better soon hopefully.
> feat: make lighter version of docs-site target

- .github/workflows/deploy-docs-prod.yaml
- .github/workflows/validate-docs-site.yaml
- .gitignore
- site/Makefile
- site/_quarto.yml
This adds an external dependency for additional private documentation. The gha and Makefiles are setup to track the `main` branch of the dependency repository.
ValidMind Employees can access this link with further explanation of why: https://www.notion.so/validmind/Docs-2-0-Site-18a19127eb1280ada461c96175d449a1?pvs=4#1c019127eb128016a11fe0eddcc368fb
> feat: extend build to include private section

- site/_quarto.yml
- site/guide/configuration/_manage-roles.qmd
- site/guide/configuration/manage-model-stakeholder-types.qmd
- site/guide/configuration/managing-users.qmd
- site/guide/model-inventory/edit-model-inventory-fields.qmd
- site/guide/model-inventory/manage-model-inventory-fields.qmd
> sc-9319
This feature is highlighted in our latest release notes, so quickly pushing out a new user guide for model stakeholder types:
Net-new page under "Managing users":
[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-9319/documentation-as-a-admin-i-am-able-to-manage/guide/configuration/manage-model-stakeholder-types.html)
Added it to the "Managing users" landing page tiles as well: 
[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-9319/documentation-as-a-admin-i-am-able-to-manage/guide/configuration/managing-users.html)
[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-9319/documentation-as-a-admin-i-am-able-to-manage/guide/model-inventory/edit-model-inventory-fields.html)
Added a section on editing model …
> Documentation: Manage model stakeholder types

- .github/workflows/deploy-docs-prod.yaml
- .github/workflows/deploy-docs-staging.yaml
- site/Makefile
We push both docs and helm chart into the same s3 bucket. We need to not delete the helm chart when we deploy the docs site. This repairs the exclude flag option to not stomp the helm chart out of existence.
Note the timing on these two actions runs:
Deploy helm chart (see list-files)
https://github.com/validmind/installation/actions/runs/14983266182/job/42092054339#step:8:12
Then Deploy Docs runs and deletes the files 
https://github.com/validmind/documentation/actions/runs/14983707903/job/42093452823
I can confirm they are not there right now.
```
AWS_PROFILE=root  aws s3 ls --recursive docs-ci-cd-prod | grep installation
2025-05-12 17:43:17      44750 site/installation/Contents.html
2025-05-12 17:43:17      57990 site/installation/Customer-managed-releases.html
2025-05-12 17:43:17 …
```
> feat: repair helm chart conflicts

- .github/workflows/deploy-docs-prod.yaml
This excludes another path in the s3 bucket for files put there by automation
> feat: make docs repo safe for omnibus

- Dockerfile
- site/scripts/docker_entrypoint.sh
This PR solves an issue I found during additional testing this morning whereby the internal manifest file was overriding the environment variables, instead of the other way around.
> Hotfix for Kind environment variable override

- .github/workflows/deploy-docs-prod.yaml
This will accommodate moving the docs site to its new location. The bucket in the new account has been backfilled with the data from the current docs site bucket.
N/A
N/A
N/A
> chore: update bucket, distro for prod docs deploy

- Dockerfile
- site/Dockerfile
This is causing a client security scanner to flap incessantly, so we should upgrade it.
> chore: upgrade libxml2

- internal/testing/variables/variables.qmd
- site/_variables.yml
connected to the following: https://github.com/validmind/installation/pull/88
story: https://app.shortcut.com/validmind/story/10469/installation-docs-to-use-variables-yml
github: 
The following Variables appeared a few times, so Beck advised me to define new variables for them:
ValidMind Admin UI and ValidMind releases
Pull down this PR: gh pr checkout 796
- Inspect _variables.yml and qmd
> Create new variable for Product name

- site/styles.css
This PR removes the CSS `max-height` constraint and slightly changes the `margin-top` for the logo area of our docs site. This change lets the logo dictate the size which in turn enables better rebranding.
The updated CSS does subtly change how our own logo is displayed but the new placement looks slightly better, IMHO, with the logo centerline now matching up to the text centerline. 
**Before**
**After**
See the screenshots I've attached. 
N/A
> Remove height constraint from navbar-brand

- site/about/overview-llm-features.qmd
This PR fixes this warning due to an unused footnote:
> Remove unused footnote

- internal/templates/videos/index.qmd
- site/_variables.yml
- site/developer/developer.css
- site/styles.css
- site/training/administrator-fundamentals/customizing-your-model-inventory.qmd
- site/training/administrator-fundamentals/onboarding-your-organization.qmd
- site/training/administrator-fundamentals/organizational-oversight-reporting.qmd
- site/training/administrator-fundamentals/using-validmind-for-model-risk-management.qmd
- site/training/developer-fundamentals/finalizing-model-documentation.qmd
- site/training/developer-fundamentals/implementing-custom-tests.qmd
- site/training/developer-fundamentals/learning-to-run-tests.qmd
- site/training/developer-fundamentals/using-validmind-for-model-development.qmd
- site/training/risk-governance-fundamentals.qmd/risk-governance-fundamentals.qmd
- site/training/training-templates/course-slides.qmd
- site/training/training.qmd
- site/training/validator-fundamentals/developing-challenger-models.qmd
- site/training/validator-fundamentals/finalizing-validation-reports.qmd
- site/training/validator-fundamentals/running-data-quality-tests.qmd
- site/training/validator-fundamentals/using-validmind-for-model-validation.qmd
This PR cherry picks the following commits into `prod`
- 5534dce3e #837
- bb7da900f #819
- ee8e09381 #796
Compare the changes in this PR against those introduced in the original commits. They should match.
N/A
> Cherry pick into `prod`

- .github/workflows/lighthouse-check.yaml
- .github/workflows/validate-docs-site.yaml
It appears https://github.com/validmind/documentation/commit/ae973d4600a1b99c0dbd94bf718fe72af37a2300#diff-97e4422bf78b64c199ffc642cb458be76ad2bd30b54a40c85846cfc7f2d35cebL63 removed the action to generate our sitemaps. Why, I'm not sure, but this PR fixes the issue. 
Without the sitemaps, the Lighthouse check will fail every time, as they have a dependency on there being a sitemap we can parse to check files. 
Relates to [sc-11350](https://app.shortcut.com/validmind/story/11350/fix-lighthouse-checks)
Proof's in the pudding: If the Lighthouse check passes, then this means we're getting the sitemaps.
> Re-add make generate-sitemap action

- .github/workflows/release_notes_check.yaml
I think I understand the mystery of the workflow I noticed in a PR last week ... it seems some lines got duplicated. This PR aims to fix the issue, using the [reposync version](https://github.com/validmind/reposync/blob/main/workflows/release_notes_check.yaml) as the canonical source. 
The release notes check should pass in this PR. 
N/A 
N/A
> Fix duplicated workflow contents

- site/index.qmd
> sc-11339
When we implemented the MVP of the homepage, we didn't use any of the required product variables. Fixed now.
Click on the LIVE PREVIEW: [**Homepage**](https://docs-staging.validmind.ai/pr_previews/beck/sc-11339/switch-new-home-page-to-use-product-variables/index.html)
> [!NOTE]
> I double-checked how the homepage looks on mobile and it's still kind of jank — we should probably add a story for this to our epic when we are done fiddling with the white-space/alignment.
n/a
n/a
> hotfix: Applied product variables to homepage

- site/_variables.yml
This PR checks out `site/_variables.yml` from `staging` to address a merge conflict.
> Add updated site/_variables.yml to prod to address merge conflict

- site/Makefile
This PR includes the Makefile from staging to avoid a merge conflict.
> Check out makefile from staging

- .github/workflows/validate-docs-site.yaml
This PR ensures that a `WARNING` like the following trips the validate workflow when we render the docs site:
```
[688/759] installation/reference/validmind-rest-api-admin.qmd 
[WARNING] Div at line 74 column 1 unclosed at line 314 column 1, closing implicitly.
```
Rel. [sc-11596](https://app.shortcut.com/validmind/story/11596/check-for-warnings-should-trip-on-warning)
There's currently a file that generates a WARNING which should cause the validate workflow to fail.
EDIT: And it does, as expected: [Workflow run](https://github.com/validmind/documentation/actions/runs/16680291497/job/47217047343?pr=878)
```
Error: Process completed with exit code 1.
```
This warning should go away after the issue is fixed in [#123](https://github.com/validmind/installation/pull/123)
> Check for WARNING in render log

- .github/workflows/validate-docs-site.yaml
- site/guide/model-workflows/_review-active-workflows.qmd
- site/notebooks/EXECUTED/test.ipynb
Fixing merge conflicts for `prod` push https://github.com/validmind/documentation/pull/883.
> Resolve merge conflicts for `prod` push #883

- README.md
> [TESTING] Merging a PR into `main-test`

- site/guide/_sidebar.yaml
- site/guide/configuration/manage-platform-notifications.qmd
- site/guide/model-workflows/manage-workflow-tasks.qmd
- site/guide/model-workflows/working-with-model-workflows.qmd
> sc-11564
Actions you can take as a user ("assigned" to you via workflows) on models via workflows now show up under **Updates**. Docs have been edited to reflect this.
Review the live previews and screenshots.
Updated the extra tab you have to click now for updates under **Updates**.
[**LIVE PREVIEW LINK**](https://docs-staging.validmind.ai/pr_previews/beck/sc-11564/documentation-my-tasks/guide/configuration/manage-platform-notifications.html#view-platform-notifications)
| Old screenshot | Screenshot of changes |
|--|--|
| <img width="958" height="290" alt="Screenshot 2025-09-03 at 10 07 21 AM" src="https://github.com/user-attachments/assets/247773fb-1a58-41a9-840e-1c50113fcfe1" />| <img width="888" height="305" alt="Screenshot 2025-09-03 at 10 07 37 AM" …
> docs: Workflow tasks in updates

- site/Makefile
- site/reference/validmind-rest-api-vm.qmd
- site/reference/vm-api.qmd
This PR points our API reference and Makefile to use the prod servers.
Relates to:
- [sc-12166](https://app.shortcut.com/validmind/story/12166/point-the-api-reference-to-production-server)
- [PR #135](https://github.com/validmind/installation/pull/135)
Proof prod is available, pretty output: 
```
❯ curl -X GET "https://api.prod.validmind.ai/vm/api/v1/models" \
-H 'accept: application/json' \
-H 'x-api-key: MY_KEY' \
-H 'x-api-secret: MY_SECRET'
{
"page": 1,
"total": 21,
"limit": 100,
"results": [
{
"cuid": "clnb0m0v300hn17iep5i1zn7t",
"name": "[Demo] Customer Churn Model",
"model_id": null,
"tiering": null,
"stakeholders": null,
"business_unit": {
"cuid": null,
"name": null,
"created_at": null
},
"use": null,
"status": {
"cuid": null,
"workflow_cuid": null,
"name": null
}, …
```
> Update API reference to use prod server

- site/Makefile
I found a bug in our Makefile where the `INSTALLATION` option always clones main. The issue was caused by a duplicate variable definition, which this PR removes. I also grouped the branch variable definitions together for clarity.
As always, the problem is ... me. I introduced the bug. 😬 I think at some point, I must have shortened the command line option names for simplicity but kept testing with `INSTALLATION_BRANCH` which also happens to work as it's the variable we use internally in the script.
Without this PR, specifying `INSTALLATION` will always clone main. You can try this and be very confused, just like me today. 
Proof the fix works: 
```
❯ make clean clone INSTALLATION=nrichers/sc-12150/turn-sso-email-info-into-topic 
...
Cloning installation repo from …
```
> Fix bug in Makefile for `INSTALLATION` option

- site/.gitignore
- site/reference/vm-api.qmd
This PR fixes an annoying behavior with our API reference search which gets interrupted by our Algolia docs site search:
- **Before**: Our Algolia docs site search steals focus when you try to search our API reference
- **After**: API reference search works as expected and no Algolia docs site search modal appears
This should be a safe, CSS-only fix that is applied only on this page.
Check out the video (first tab = before; second tab = after):
https://github.com/user-attachments/assets/b4d34396-5210-459d-8d23-9cd5e600bc2e
Relates to [sc-12201](https://app.shortcut.com/validmind/story/12201/disable-algolia-search-on-api-reference-pages?vc_group_by=day&ct_workflow=all&cf_workflow=500004900), https://github.com/validmind/installation/pull/139
> Bug bash: nrichers/sc 12201/disable algolia search on api reference pages

- site/guide/templates/_add-text-blocks.qmd
- site/guide/templates/customize-document-templates.qmd
- site/guide/templates/manage-document-templates.qmd
- site/guide/templates/manage-text-block-library.qmd
> sc-12028
You can now add shared text blocks to your document templates through the YAML editor. Docs have been updated to reflect this functionality.
Net-new section under Edit YAML templates: [**Add text blocks to templates**](https://docs-staging.validmind.ai/pr_previews/beck/sc-12028/documentation-ability-to-add-library-blocks/guide/templates/customize-document-templates.html#add-text-blocks-to-templates) (Click for live preview.)
Screencaps:
I also moved "Duplicate templates" from the customization page into Manage document templates because it actually made more sense there, and also cleaned up the page: [**Manage document templates**](https://docs-staging.validmind.ai/pr_previews/beck/sc-12028/documentation-ability-to-add-library-blocks/guide/templates/manage-document-templates.htm …
> docs: Add shared text blocks to YAML templates

- site/guide/model-documentation/_check-model-documentation.qmd
- site/guide/model-documentation/_document-checker.qmd
- site/guide/model-documentation/check-documentation-for-compliance.qmd
- site/guide/templates/_add-assessment-questions.qmd
- site/guide/templates/_add-assessments.qmd
- site/guide/templates/_add-regulations-policies.qmd
- site/guide/templates/_assessments.qmd
- site/guide/templates/_regulations-policies.qmd
- site/guide/templates/customize-virtual-document-validator.qmd
- site/training/administrator-fundamentals/administrator-fundamentals-register.qmd
- site/training/administrator-fundamentals/using-validmind-for-model-risk-management.qmd
- site/training/common-slides/_document-checker.qmd
- site/training/developer-fundamentals/finalizing-model-documentation.qmd
- site/training/program/learning-paths.qmd
> sc-12007
Wrapping up the Virtual Document Validator/Document Checker latest phase release where we can now upload a PDF to automatically generate questions. Docs and training slides have been updated to reflect this functionality as the feature is now "complete" for the moment as planned.
Review the live previews and screencaps:
- [**Customize Virtual Document Validator**](https://docs-staging.validmind.ai/pr_previews/beck/sc-12007/documentation-for-byod/guide/templates/customize-virtual-document-validator.html#add-or-edit-assessment-questions)
- Administrator Fundamentals: [**Using ValidMind for Model Risk Management**](https://docs-staging.validmind.ai/pr_previews/beck/sc-12007/documentation-for-byod/training/administrator-fundamentals/using-validmind-for-model-risk-management.html#/ma …
> docs & training: Virtual Document Validator, regulations & policies set up update

- site/guide/templates/_add-assessment-questions.qmd
Feature-flag for this functionality is not slated to be released in the current sprint. Commenting out the instructions added in https://github.com/validmind/documentation/pull/973 for now.
Click the live preview: [**Customize Virtual Document Validator**
](https://docs-staging.validmind.ai/pr_previews/beck/hide-vdv-pdf-upload/guide/templates/customize-virtual-document-validator.html#add-or-edit-assessment-questions)
| HIDDEN | SHOWN |
|--|--|
| <img width="1259" height="722" alt="Screenshot 2025-10-03 at 11 54 13 AM" src="https://github.com/user-attachments/assets/717e095d-80ac-4c99-9e84-f3c87a682896" /><img width="947" height="408" alt="Screenshot 2025-10-03 at 11 54 23 AM" src="https://github.com/user-attachments/assets/57812498-9e1d-4a18-b0e5-315e163e7fc8" /> | <img width="1265" …
> docs hotfix: Hiding PDF upload instructions for VDV
